# Automatically generated by configure - do not modify
SRC_PATH=/home/vagrant/src/qemu/pkg-qemu/roms/vgabios
CC=gcc
BCC=bcc
CPP=cpp
OBJCOPY=objcopy
IASL=iasl
HOST_CC=gcc
LD=ld
# Automatically generated by configure - do not modify
SRC_PATH=/home/vagrant/src/qemu/pkg-qemu/roms/vgabios
CC=gcc
BCC=bcc
CPP=cpp
OBJCOPY=objcopy
IASL=iasl
HOST_CC=gcc
LD=ld
