#! /bin/sh
#
# List of optional features which should be enabled
# during debian build of qemu package.
# This is a shell code AND data file.  Run with two arguments,
# OS (linux|kfreebsd|...) and Arch (i386|mips|...).

sed -e '1,/^__DATA__/D' \
 -e 's/#.*//' -e '/^[^a-z]/D' $0 |
while read opt cond; do
  [ -n "$opt" ] || continue
  x=
  [ -z "$cond" ] && x=y
  [ -n "$x" ] || eval "case \"$1\" in $cond) x=y;; esac"
  [ -n "$x" ] || eval "case \"$2\" in $cond) x=y;; esac"
  [ -n "$x" ] || eval "case \"$1-$2\" in $cond) x=y;; esac"
  [ -z "$x" ] || echo --$opt
done

exit

__DATA__
# Format of the data portion is a feature (configure option),
# followed with a shell-style "case" wildcard for os, arch or os:arch
# (linux:i386, kfreebsd:amd64 etc).
# Empty lines and everything after "#" char are ignored.

# audio drivers
# pa is usually installed so we want it first without any compat layer
# alsa is the native system on linux (and oss is native on kfreebsd)
audio-drv-list=pa,alsa,sdl,oss	linux
audio-drv-list=pa,oss,sdl	kfreebsd
# enable all available audio devices
audio-card-list=ac97,es1370,sb16,cs4231a,adlib,gus,hda

# virtfs needs libcap and libcap-ng, linux-only
enable-virtfs	linux
enable-cap-ng	linux	# is virtfs enough?
enable-attr	# linux-specific?

# SDL is always enabled
enable-sdl
# vnc and related options are always enabled
enable-vnc
enable-vnc-tls
enable-vnc-sasl
enable-vnc-jpeg
enable-vnc-png

enable-curses
enable-curl
enable-fdt
enable-bluez		linux
enable-uuid
enable-vde
enable-libiscsi

enable-linux-aio	linux
enable-xfsctl		linux
# somehow seccomp is linux-x86-specific
enable-seccomp		linux-amd64 | linux-i386

# kvm is linux-specific
enable-kvm	linux
enable-vhost-net linux	# is vhost-net linux-specific?
enable-xen	amd64|i386

# should we enable spice on more arches?
enable-spice	amd64|i386

#enable-rbd	# rbd isn't enabled yet
#enable-smartcard-nss	# requires libnss3-dev and libtool
enable-usb-redir	linux
#enable-seccomp		# XXX todo
#enable-glusterfs	# XXX todo
