debian/qemu-ifdown etc/
debian/tmp/usr/share/man/man1/qemu-system.1
debian/tmp/usr/share/qemu/keymaps
debian/tmp/usr/share/qemu/trace-events-all
pc-bios/qemu-icon.bmp usr/share/qemu
pc-bios/qemu_logo_no_text.svg usr/share/qemu
# qemu-doc is duplicated here and in qemu metapackage
debian/tmp/usr/share/doc/qemu/qemu-doc.* usr/share/doc/qemu-system-common
debian/tmp/usr/share/man/man7/qemu-qmp-ref.7
debian/tmp/usr/share/doc/qemu/qemu-qmp-ref.* usr/share/doc/qemu-system-common
debian/qemu-kvm-init /usr/share/qemu/init
